version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ai_interviewer_server
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    env_file:
      - ./server/.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ai_interviewer_client
    ports:
      - "80:80"
    depends_on:
      - server
